# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2efff463e42be1cfb23ae7b038f1a3e8df5345086a462bcfa913825fadc498f6e50afb32bbd7655d39a279cea100cb41f8ce350c2df92f6a51945a1ac3e98c53

test:
  secret_key_base: 06369a698efce06fccf963664ddf522dd01efa89827637764f8f4fdf69f0fa18e83588b065677ac945641202388c3d8af45735d5749bc2207016f7ede43b2ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
